# Site settings
author: Tatiana Mojica 
title: Reviewing with Sinatra 
header-img: img/home-bg.png
email: tatiana.mojica@bustle.com
copyright_name: Tatiana Mojica 
description: > # this means to ignore newlines until "baseurl:"
  Brooklyn Eateries- Believe the Hype! 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tatscru

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
